"""empty message

Revision ID: 9aa6078cdbb8
Revises: 13aeba30ebbe
Create Date: 2020-05-08 22:58:37.722033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aa6078cdbb8'
down_revision = '13aeba30ebbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_groupname'), 'group', ['groupname'], unique=True)
    op.create_table('profil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profilname', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profil_profilname'), 'profil', ['profilname'], unique=True)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sales_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_clientname'), 'client', ['clientname'], unique=True)
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_index(op.f('ix_client_clientname'), table_name='client')
    op.drop_table('client')
    op.drop_table('service')
    op.drop_index(op.f('ix_profil_profilname'), table_name='profil')
    op.drop_table('profil')
    op.drop_index(op.f('ix_group_groupname'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
