"""empty message

Revision ID: bfc4ef3be8d1
Revises: 9aa6078cdbb8
Create Date: 2020-05-10 18:06:40.812132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc4ef3be8d1'
down_revision = '9aa6078cdbb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equip_ref', sa.String(length=128), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('serial', sa.String(length=128), nullable=True),
    sa.Column('equip_type', sa.String(length=64), nullable=True),
    sa.Column('product_num', sa.String(length=128), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('warranty', sa.Boolean(), nullable=True),
    sa.Column('real_cost', sa.Numeric(precision=8, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_equip_ref'), 'equipment', ['equip_ref'], unique=True)
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=True),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('id_equipment', sa.Integer(), nullable=True),
    sa.Column('to_be_charged', sa.Boolean(), nullable=True),
    sa.Column('sales_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('invoice_num', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['client.id'], ),
    sa.ForeignKeyConstraint(['id_equipment'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sales_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_ticket_id'), 'ticket', ['ticket_id'], unique=True)
    op.add_column('service', sa.Column('realcost', sa.Numeric(precision=8, asdecimal=False), nullable=True))
    op.add_column('service', sa.Column('service_type', sa.String(length=64), nullable=True))
    op.add_column('service', sa.Column('servicename', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_service_servicename'), 'service', ['servicename'], unique=True)
    op.add_column('user', sa.Column('firstname', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('id_group', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('id_profil', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=True))
    op.create_foreign_key(None, 'user', 'group', ['id_group'], ['id'])
    op.create_foreign_key(None, 'user', 'profil', ['id_profil'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'id_profil')
    op.drop_column('user', 'id_group')
    op.drop_column('user', 'firstname')
    op.drop_index(op.f('ix_service_servicename'), table_name='service')
    op.drop_column('service', 'servicename')
    op.drop_column('service', 'service_type')
    op.drop_column('service', 'realcost')
    op.drop_index(op.f('ix_ticket_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    op.drop_index(op.f('ix_equipment_equip_ref'), table_name='equipment')
    op.drop_table('equipment')
    # ### end Alembic commands ###
